import * as React from "react";
import { NextPage } from "next";
import Box from "@mui/material/Box";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import { useRouter } from "next/router";
import TopBar from "./layouts/TopBar";
import Loading from "./layouts/Loading";

interface Props {
  children: React.ReactNode;
  title?: string;
}

interface UserInfo {
  auth: { userInfo: object };
}

const Default: NextPage<Props> = ({ children, title }): React.ReactElement => {
  const dispatch = useDispatch();
  const router = useRouter();
  const res: any = useSelector<UserInfo>((state) => state.auth.userInfo);

  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    if (res?.token === "") {
      router.push("/auth");
    } else {
      setLoading(false);
    }
  }, []);

  return loading ? (
    <Loading />
  ) : (
    <Box>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <Box>
        <main>{children}</main>
      </Box>
    </Box>
  );
};

export default Default;
