import * as React from "react";
import { NextPage } from "next";
import Box from "@mui/material/Box";
import Head from "next/head";

interface Props {
  children: React.ReactNode;
  title: string;
}

const Default: NextPage<Props> = ({ children, title }): React.ReactElement => {
  return (
    <Box>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <main>{children}</main>
      </Box>
    </Box>
  );
};

export default Default;
